### ISSUE TITLE
Mod Proposal for Known and Collected

### ISSUE THREAD

**Issue by Wookieebane** [puchy9696/Agile-Zomboid#12]
### Name
Known and Collected
### Steam IDs
Workshop ID: 2881764317
Mod ID: KnownAndCollected
### Pitch
Can't remember if you read tailoring one? Worry no more! This mod will show you if you've read, never read, or want to read a book later, this mod is for you :)

**Comment by chef-slowcook** [comment]
Will be Added to the server on next restart.

**Comment by chef-slowcook** [comment]
Added to ini
